{% set data = load_setup_py_data() %}

package:
  name: uwsift
  version: {{ data.get('version') }}

source:
  path: ../../
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python {{PY_VER}}*,>=3.6
    - setuptools
    - pip
#    - cython >=0.17 # [win]
#    # this is only needed because of a weird bug with netcdf4
#    # https://github.com/conda-forge/netcdf4-feedstock/issues/33
#    - cython >=0.19 # [unix]

  run:
    - python >=3.6
    - setuptools
    - pip
    - numpy >=1.12
    - hdf5
    - rasterio
    - matplotlib
    - numba >=0.30
    - pyproj >=1.9.4
    - vispy >=0.6.0.dev1
    - goesr >=0.4.2 # via Ray Garcia, on sift channel
    - pyopengl
    - netcdf4
    - h5py
    - imageio
    - imageio-ffmpeg
    - ffmpeg
    - pillow
    - pyshp
    - pyqtgraph
    - shapely
    - sqlalchemy
    - pyqt >=5.9
    - appdirs
    - pyyaml
    - satpy >=0.10.0a0
    - pygrib  # [not win]
    - scikit-image

test:
  commands:
    - python -m uwsift -h
    - python -c "from rasterio import Affine"
    - python -c "from PyQt5 import QtGui, QtCore, QWidgets"
    - python -c "from netCDF4 import Dataset"
    - python -c "import h5py"

about:
  #home: The package home page
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: 'Visualization Tool for Geostationary satellite imagery data'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

