{% set version = "0.6.0.dev0" %}

package:
  name: vispy
  version: {{ version }}

source:
  git_url: https://github.com/vispy/vispy.git
  git_rev: a6ec64bb7b56739b463e3c16245a31940ca4f5f7
  patches:
    - ctypes_fontconfig.diff

build:
  number: 3
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - fontconfig  # [unix]
    - {{ compiler('c') }}
    - cython

  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - fontconfig  # [unix]
    - scikit-image

test:
  imports:
    - vispy

about:
  home: http://vispy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'VisPy is a high-performance interactive 2D/3D data visualization library.'
