# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pov_main.ui'
#
# Created: Wed Sep 30 09:40:33 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1366, 998)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mainWidgets = QtGui.QTabWidget(self.centralwidget)
        self.mainWidgets.setObjectName(_fromUtf8("mainWidgets"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.mainWidgets.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.mainWidgets.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.mainWidgets)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.progressBar = QtGui.QProgressBar(self.groupBox)
        self.progressBar.setMaximumSize(QtCore.QSize(256, 16777215))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout.addWidget(self.progressBar)
        self.queueButton = QtGui.QToolButton(self.groupBox)
        self.queueButton.setObjectName(_fromUtf8("queueButton"))
        self.horizontalLayout.addWidget(self.queueButton)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.animationSlider = QtGui.QSlider(self.groupBox)
        self.animationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.animationSlider.setObjectName(_fromUtf8("animationSlider"))
        self.horizontalLayout.addWidget(self.animationSlider)
        self.animBack = QtGui.QToolButton(self.groupBox)
        self.animBack.setObjectName(_fromUtf8("animBack"))
        self.horizontalLayout.addWidget(self.animBack)
        self.animPlayPause = QtGui.QToolButton(self.groupBox)
        self.animPlayPause.setObjectName(_fromUtf8("animPlayPause"))
        self.horizontalLayout.addWidget(self.animPlayPause)
        self.animForward = QtGui.QToolButton(self.groupBox)
        self.animForward.setObjectName(_fromUtf8("animForward"))
        self.horizontalLayout.addWidget(self.animForward)
        self.line_2 = QtGui.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout.addWidget(self.line_2)
        self.cursorProbeText = QtGui.QLabel(self.groupBox)
        self.cursorProbeText.setMinimumSize(QtCore.QSize(128, 0))
        self.cursorProbeText.setMaximumSize(QtCore.QSize(256, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Andale Mono"))
        font.setPointSize(14)
        self.cursorProbeText.setFont(font)
        self.cursorProbeText.setObjectName(_fromUtf8("cursorProbeText"))
        self.horizontalLayout.addWidget(self.cursorProbeText)
        self.verticalLayout_2.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.probeAPane = QtGui.QDockWidget(MainWindow)
        self.probeAPane.setObjectName(_fromUtf8("probeAPane"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.probeAPane.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.probeAPane)
        self.probeBPane = QtGui.QDockWidget(MainWindow)
        self.probeBPane.setObjectName(_fromUtf8("probeBPane"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.probeBPane.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.probeBPane)
        self.layersPane = QtGui.QDockWidget(MainWindow)
        self.layersPane.setObjectName(_fromUtf8("layersPane"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.layerSetTabs = QtGui.QTabWidget(self.dockWidgetContents_5)
        self.layerSetTabs.setObjectName(_fromUtf8("layerSetTabs"))
        self.layerSet1Tab = QtGui.QWidget()
        self.layerSet1Tab.setObjectName(_fromUtf8("layerSet1Tab"))
        self.layerSet1Table = QtGui.QTableView(self.layerSet1Tab)
        self.layerSet1Table.setGeometry(QtCore.QRect(0, 0, 285, 450))
        self.layerSet1Table.setObjectName(_fromUtf8("layerSet1Table"))
        self.layerSetTabs.addTab(self.layerSet1Tab, _fromUtf8(""))
        self.layerSet2Tab = QtGui.QWidget()
        self.layerSet2Tab.setObjectName(_fromUtf8("layerSet2Tab"))
        self.layerSet2Table = QtGui.QTableView(self.layerSet2Tab)
        self.layerSet2Table.setGeometry(QtCore.QRect(0, 0, 285, 450))
        self.layerSet2Table.setObjectName(_fromUtf8("layerSet2Table"))
        self.layerSetTabs.addTab(self.layerSet2Tab, _fromUtf8(""))
        self.layerSet3Tab = QtGui.QWidget()
        self.layerSet3Tab.setObjectName(_fromUtf8("layerSet3Tab"))
        self.layerSet3Table = QtGui.QTableView(self.layerSet3Tab)
        self.layerSet3Table.setGeometry(QtCore.QRect(0, 0, 285, 450))
        self.layerSet3Table.setObjectName(_fromUtf8("layerSet3Table"))
        self.layerSetTabs.addTab(self.layerSet3Tab, _fromUtf8(""))
        self.layerSet4Tab = QtGui.QWidget()
        self.layerSet4Tab.setObjectName(_fromUtf8("layerSet4Tab"))
        self.layerSet4Table = QtGui.QTableView(self.layerSet4Tab)
        self.layerSet4Table.setGeometry(QtCore.QRect(0, 0, 285, 450))
        self.layerSet4Table.setObjectName(_fromUtf8("layerSet4Table"))
        self.layerSetTabs.addTab(self.layerSet4Tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.layerSetTabs)
        self.layersPane.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.layersPane)
        self.layerConfigPane = QtGui.QDockWidget(MainWindow)
        self.layerConfigPane.setObjectName(_fromUtf8("layerConfigPane"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayoutWidget = QtGui.QWidget(self.dockWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 311, 171))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.layerNameEdit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.layerNameEdit.setObjectName(_fromUtf8("layerNameEdit"))
        self.gridLayout.addWidget(self.layerNameEdit, 0, 0, 1, 1)
        self.colorBarButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.colorBarButton.setMinimumSize(QtCore.QSize(0, 32))
        self.colorBarButton.setObjectName(_fromUtf8("colorBarButton"))
        self.gridLayout.addWidget(self.colorBarButton, 1, 0, 1, 1)
        self.layerConfigPane.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.layerConfigPane)

        self.retranslateUi(MainWindow)
        self.layerSetTabs.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.mainWidgets.setTabText(self.mainWidgets.indexOf(self.tab), _translate("MainWindow", "Tab 1", None))
        self.mainWidgets.setTabText(self.mainWidgets.indexOf(self.tab_2), _translate("MainWindow", "Tab 2", None))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox", None))
        self.progressBar.setToolTip(_translate("MainWindow", "Background Activity", None))
        self.queueButton.setText(_translate("MainWindow", "...", None))
        self.animationSlider.setToolTip(_translate("MainWindow", "Animation", None))
        self.animBack.setText(_translate("MainWindow", "...", None))
        self.animPlayPause.setText(_translate("MainWindow", "...", None))
        self.animForward.setText(_translate("MainWindow", "...", None))
        self.cursorProbeText.setToolTip(_translate("MainWindow", "Value under cursor", None))
        self.cursorProbeText.setText(_translate("MainWindow", "TextLabel", None))
        self.probeAPane.setWindowTitle(_translate("MainWindow", "A Probe", None))
        self.probeBPane.setWindowTitle(_translate("MainWindow", "B Probe", None))
        self.layersPane.setWindowTitle(_translate("MainWindow", "Layers", None))
        self.layerSetTabs.setTabText(self.layerSetTabs.indexOf(self.layerSet1Tab), _translate("MainWindow", "1", None))
        self.layerSetTabs.setTabToolTip(self.layerSetTabs.indexOf(self.layerSet1Tab), _translate("MainWindow", "Layer Set 1", None))
        self.layerSetTabs.setTabText(self.layerSetTabs.indexOf(self.layerSet2Tab), _translate("MainWindow", "2", None))
        self.layerSetTabs.setTabToolTip(self.layerSetTabs.indexOf(self.layerSet2Tab), _translate("MainWindow", "Layer Set 2", None))
        self.layerSetTabs.setTabText(self.layerSetTabs.indexOf(self.layerSet3Tab), _translate("MainWindow", "3", None))
        self.layerSetTabs.setTabToolTip(self.layerSetTabs.indexOf(self.layerSet3Tab), _translate("MainWindow", "Layer Set 3", None))
        self.layerSetTabs.setTabText(self.layerSetTabs.indexOf(self.layerSet4Tab), _translate("MainWindow", "4", None))
        self.layerSetTabs.setTabToolTip(self.layerSetTabs.indexOf(self.layerSet4Tab), _translate("MainWindow", "Layer Set 4", None))
        self.layerConfigPane.setWindowTitle(_translate("MainWindow", "Layer Details", None))
        self.layerNameEdit.setText(_translate("MainWindow", "Layer Name", None))
        self.colorBarButton.setText(_translate("MainWindow", "ColorBar", None))

