# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_file_wizard.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_openFileWizard(object):
    def setupUi(self, openFileWizard):
        openFileWizard.setObjectName(_fromUtf8("openFileWizard"))
        openFileWizard.resize(599, 461)
        openFileWizard.setSizeGripEnabled(True)
        openFileWizard.setModal(True)
        openFileWizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        openFileWizard.setOptions(QtGui.QWizard.CancelButtonOnLeft)
        openFileWizard.setTitleFormat(QtCore.Qt.AutoText)
        openFileWizard.setSubTitleFormat(QtCore.Qt.AutoText)
        self.fileSelectionPage = AnyWizardPage()
        self.fileSelectionPage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fileSelectionPage.setObjectName(_fromUtf8("fileSelectionPage"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.fileSelectionPage)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.readerLabel = QtGui.QLabel(self.fileSelectionPage)
        self.readerLabel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.readerLabel.setObjectName(_fromUtf8("readerLabel"))
        self.horizontalLayout_3.addWidget(self.readerLabel)
        self.readerComboBox = QtGui.QComboBox(self.fileSelectionPage)
        self.readerComboBox.setObjectName(_fromUtf8("readerComboBox"))
        self.horizontalLayout_3.addWidget(self.readerComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.inputFilesLabel = QtGui.QLabel(self.fileSelectionPage)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.inputFilesLabel.setFont(font)
        self.inputFilesLabel.setObjectName(_fromUtf8("inputFilesLabel"))
        self.verticalLayout_3.addWidget(self.inputFilesLabel)
        self.fileList = QtGui.QListWidget(self.fileSelectionPage)
        self.fileList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.fileList.setObjectName(_fromUtf8("fileList"))
        self.verticalLayout_3.addWidget(self.fileList)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.addButton = QtGui.QPushButton(self.fileSelectionPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setMinimumSize(QtCore.QSize(25, 25))
        self.addButton.setMaximumSize(QtCore.QSize(25, 25))
        self.addButton.setCheckable(False)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.horizontalLayout.addWidget(self.addButton)
        spacerItem = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.removeButton = QtGui.QPushButton(self.fileSelectionPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeButton.sizePolicy().hasHeightForWidth())
        self.removeButton.setSizePolicy(sizePolicy)
        self.removeButton.setMinimumSize(QtCore.QSize(25, 25))
        self.removeButton.setMaximumSize(QtCore.QSize(25, 25))
        self.removeButton.setObjectName(_fromUtf8("removeButton"))
        self.horizontalLayout.addWidget(self.removeButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        openFileWizard.addPage(self.fileSelectionPage)
        self.productSelectionPage = AnyWizardPage()
        self.productSelectionPage.setObjectName(_fromUtf8("productSelectionPage"))
        self.verticalLayout = QtGui.QVBoxLayout(self.productSelectionPage)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.selectByTabWidget = QtGui.QTabWidget(self.productSelectionPage)
        self.selectByTabWidget.setObjectName(_fromUtf8("selectByTabWidget"))
        self.selectByParameters = QtGui.QWidget()
        self.selectByParameters.setObjectName(_fromUtf8("selectByParameters"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.selectByParameters)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.selectByNameLayout = QtGui.QVBoxLayout()
        self.selectByNameLayout.setObjectName(_fromUtf8("selectByNameLayout"))
        self.selectByNameLabel = QtGui.QLabel(self.selectByParameters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.selectByNameLabel.setFont(font)
        self.selectByNameLabel.setObjectName(_fromUtf8("selectByNameLabel"))
        self.selectByNameLayout.addWidget(self.selectByNameLabel)
        self.selectByNameList = QtGui.QListWidget(self.selectByParameters)
        self.selectByNameList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.selectByNameList.setObjectName(_fromUtf8("selectByNameList"))
        self.selectByNameLayout.addWidget(self.selectByNameList)
        self.horizontalLayout_2.addLayout(self.selectByNameLayout)
        self.selectByLevelLayout = QtGui.QVBoxLayout()
        self.selectByLevelLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.selectByLevelLayout.setObjectName(_fromUtf8("selectByLevelLayout"))
        self.selectByLevelLabel = QtGui.QLabel(self.selectByParameters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.selectByLevelLabel.setFont(font)
        self.selectByLevelLabel.setObjectName(_fromUtf8("selectByLevelLabel"))
        self.selectByLevelLayout.addWidget(self.selectByLevelLabel)
        self.selectByLevelList = QtGui.QListWidget(self.selectByParameters)
        self.selectByLevelList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.selectByLevelList.setObjectName(_fromUtf8("selectByLevelList"))
        self.selectByLevelLayout.addWidget(self.selectByLevelList)
        self.horizontalLayout_2.addLayout(self.selectByLevelLayout)
        self.selectByTabWidget.addTab(self.selectByParameters, _fromUtf8(""))
        self.selectByID = QtGui.QWidget()
        self.selectByID.setObjectName(_fromUtf8("selectByID"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.selectByID)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.selectIDTable = QtGui.QTableWidget(self.selectByID)
        self.selectIDTable.setDragEnabled(False)
        self.selectIDTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.selectIDTable.setObjectName(_fromUtf8("selectIDTable"))
        self.selectIDTable.setColumnCount(0)
        self.selectIDTable.setRowCount(0)
        self.verticalLayout_5.addWidget(self.selectIDTable)
        self.selectByTabWidget.addTab(self.selectByID, _fromUtf8(""))
        self.verticalLayout.addWidget(self.selectByTabWidget)
        openFileWizard.addPage(self.productSelectionPage)
        self.summaryPage = QtGui.QWizardPage()
        self.summaryPage.setObjectName(_fromUtf8("summaryPage"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.summaryPage)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.productSummaryText = QtGui.QTextBrowser(self.summaryPage)
        self.productSummaryText.setEnabled(True)
        self.productSummaryText.setObjectName(_fromUtf8("productSummaryText"))
        self.verticalLayout_4.addWidget(self.productSummaryText)
        openFileWizard.addPage(self.summaryPage)

        self.retranslateUi(openFileWizard)
        self.selectByTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(openFileWizard)

    def retranslateUi(self, openFileWizard):
        openFileWizard.setWindowTitle(_translate("openFileWizard", "Open File Wizard", None))
        self.fileSelectionPage.setTitle(_translate("openFileWizard", "Select Files", None))
        self.fileSelectionPage.setSubTitle(_translate("openFileWizard", "Add data files to be opened", None))
        self.readerLabel.setText(_translate("openFileWizard", "Reader:", None))
        self.inputFilesLabel.setText(_translate("openFileWizard", "Input Files", None))
        self.fileList.setSortingEnabled(True)
        self.addButton.setToolTip(_translate("openFileWizard", "Add files/dirs to list", None))
        self.addButton.setText(_translate("openFileWizard", "+", None))
        self.removeButton.setToolTip(_translate("openFileWizard", "Remove file from list", None))
        self.removeButton.setText(_translate("openFileWizard", "-", None))
        self.productSelectionPage.setTitle(_translate("openFileWizard", "Select Products", None))
        self.productSelectionPage.setSubTitle(_translate("openFileWizard", "Select products to add", None))
        self.selectByNameLabel.setText(_translate("openFileWizard", "Name", None))
        self.selectByLevelLabel.setText(_translate("openFileWizard", "Level", None))
        self.selectByTabWidget.setTabText(self.selectByTabWidget.indexOf(self.selectByParameters), _translate("openFileWizard", "Properties", None))
        self.selectIDTable.setSortingEnabled(False)
        self.selectByTabWidget.setTabText(self.selectByTabWidget.indexOf(self.selectByID), _translate("openFileWizard", "List", None))
        self.summaryPage.setTitle(_translate("openFileWizard", "Products Summary", None))
        self.summaryPage.setSubTitle(_translate("openFileWizard", "Verify the products that will be loaded", None))

from sift.ui.custom_widgets import AnyWizardPage
