# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_rgb_layer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig)


class Ui_config_rgb_layer(object):
    def setupUi(self, config_rgb_layer):
        config_rgb_layer.setObjectName("config_rgb_layer")
        config_rgb_layer.resize(421, 447)
        self.verticalLayout = QtWidgets.QVBoxLayout(config_rgb_layer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(config_rgb_layer)
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboRed = QtWidgets.QComboBox(self.groupBox_3)
        self.comboRed.setGeometry(QtCore.QRect(10, 20, 380, 26))
        self.comboRed.setObjectName("comboRed")
        self.slideMinRed = QtWidgets.QSlider(self.groupBox_3)
        self.slideMinRed.setGeometry(QtCore.QRect(10, 50, 380, 22))
        self.slideMinRed.setMaximum(32767)
        self.slideMinRed.setOrientation(QtCore.Qt.Horizontal)
        self.slideMinRed.setObjectName("slideMinRed")
        self.slideMaxRed = QtWidgets.QSlider(self.groupBox_3)
        self.slideMaxRed.setGeometry(QtCore.QRect(10, 80, 380, 22))
        self.slideMaxRed.setMaximum(32767)
        self.slideMaxRed.setOrientation(QtCore.Qt.Horizontal)
        self.slideMaxRed.setObjectName("slideMaxRed")
        self.redGammaSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.redGammaSpinBox.setGeometry(QtCore.QRect(70, 110, 62, 24))
        self.redGammaSpinBox.setObjectName("redGammaSpinBox")
        self.redGammaLabel = QtWidgets.QLabel(self.groupBox_3)
        self.redGammaLabel.setGeometry(QtCore.QRect(10, 110, 56, 24))
        self.redGammaLabel.setObjectName("redGammaLabel")
        self.comboRed.raise_()
        self.slideMinRed.raise_()
        self.slideMaxRed.raise_()
        self.redGammaSpinBox.raise_()
        self.redGammaLabel.raise_()
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(config_rgb_layer)
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboGreen = QtWidgets.QComboBox(self.groupBox_2)
        self.comboGreen.setGeometry(QtCore.QRect(10, 20, 380, 26))
        self.comboGreen.setObjectName("comboGreen")
        self.slideMinGreen = QtWidgets.QSlider(self.groupBox_2)
        self.slideMinGreen.setGeometry(QtCore.QRect(10, 50, 380, 22))
        self.slideMinGreen.setMaximum(32767)
        self.slideMinGreen.setOrientation(QtCore.Qt.Horizontal)
        self.slideMinGreen.setObjectName("slideMinGreen")
        self.slideMaxGreen = QtWidgets.QSlider(self.groupBox_2)
        self.slideMaxGreen.setGeometry(QtCore.QRect(10, 80, 380, 22))
        self.slideMaxGreen.setMaximum(32767)
        self.slideMaxGreen.setOrientation(QtCore.Qt.Horizontal)
        self.slideMaxGreen.setObjectName("slideMaxGreen")
        self.greenGammaLabel = QtWidgets.QLabel(self.groupBox_2)
        self.greenGammaLabel.setGeometry(QtCore.QRect(10, 110, 56, 24))
        self.greenGammaLabel.setObjectName("greenGammaLabel")
        self.greenGammaSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.greenGammaSpinBox.setGeometry(QtCore.QRect(70, 110, 62, 24))
        self.greenGammaSpinBox.setObjectName("greenGammaSpinBox")
        self.comboGreen.raise_()
        self.slideMinGreen.raise_()
        self.slideMaxGreen.raise_()
        self.groupBox_3.raise_()
        self.groupBox_3.raise_()
        self.greenGammaLabel.raise_()
        self.greenGammaSpinBox.raise_()
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(config_rgb_layer)
        self.groupBox.setObjectName("groupBox")
        self.comboBlue = QtWidgets.QComboBox(self.groupBox)
        self.comboBlue.setGeometry(QtCore.QRect(10, 20, 380, 26))
        self.comboBlue.setObjectName("comboBlue")
        self.slideMaxBlue = QtWidgets.QSlider(self.groupBox)
        self.slideMaxBlue.setGeometry(QtCore.QRect(10, 80, 380, 22))
        self.slideMaxBlue.setMaximum(32767)
        self.slideMaxBlue.setOrientation(QtCore.Qt.Horizontal)
        self.slideMaxBlue.setObjectName("slideMaxBlue")
        self.slideMinBlue = QtWidgets.QSlider(self.groupBox)
        self.slideMinBlue.setGeometry(QtCore.QRect(10, 50, 380, 22))
        self.slideMinBlue.setMaximum(32767)
        self.slideMinBlue.setOrientation(QtCore.Qt.Horizontal)
        self.slideMinBlue.setObjectName("slideMinBlue")
        self.blueGammaLabel = QtWidgets.QLabel(self.groupBox)
        self.blueGammaLabel.setGeometry(QtCore.QRect(10, 110, 56, 24))
        self.blueGammaLabel.setObjectName("blueGammaLabel")
        self.blueGammaSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.blueGammaSpinBox.setGeometry(QtCore.QRect(70, 110, 62, 24))
        self.blueGammaSpinBox.setObjectName("blueGammaSpinBox")
        self.comboBlue.raise_()
        self.slideMaxBlue.raise_()
        self.slideMinBlue.raise_()
        self.groupBox_3.raise_()
        self.blueGammaLabel.raise_()
        self.blueGammaSpinBox.raise_()
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(config_rgb_layer)
        QtCore.QMetaObject.connectSlotsByName(config_rgb_layer)

    def retranslateUi(self, config_rgb_layer):
        config_rgb_layer.setWindowTitle(_translate("config_rgb_layer", "Form", None))
        self.groupBox_3.setTitle(_translate("config_rgb_layer", "Red", None))
        self.comboRed.setToolTip(_translate("config_rgb_layer", "Red", None))
        self.comboRed.setStatusTip(_translate("config_rgb_layer", "Red channel", None))
        self.redGammaLabel.setText(_translate("config_rgb_layer", "Gamma: ", None))
        self.groupBox_2.setTitle(_translate("config_rgb_layer", "Green", None))
        self.comboGreen.setToolTip(_translate("config_rgb_layer", "Green", None))
        self.comboGreen.setStatusTip(_translate("config_rgb_layer", "Green channel", None))
        self.greenGammaLabel.setText(_translate("config_rgb_layer", "Gamma: ", None))
        self.groupBox.setTitle(_translate("config_rgb_layer", "Blue", None))
        self.comboBlue.setToolTip(_translate("config_rgb_layer", "Blue", None))
        self.comboBlue.setStatusTip(_translate("config_rgb_layer", "Blue channel", None))
        self.blueGammaLabel.setText(_translate("config_rgb_layer", "Gamma: ", None))
