# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pov_main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1397, 800)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.panZoomToolButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panZoomToolButton.sizePolicy().hasHeightForWidth())
        self.panZoomToolButton.setSizePolicy(sizePolicy)
        self.panZoomToolButton.setMinimumSize(QtCore.QSize(0, 0))
        self.panZoomToolButton.setCheckable(True)
        self.panZoomToolButton.setChecked(True)
        self.panZoomToolButton.setAutoExclusive(False)
        self.panZoomToolButton.setAutoRaise(False)
        self.panZoomToolButton.setObjectName("panZoomToolButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.panZoomToolButton)
        self.horizontalLayout_2.addWidget(self.panZoomToolButton)
        self.pointSelectButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pointSelectButton.sizePolicy().hasHeightForWidth())
        self.pointSelectButton.setSizePolicy(sizePolicy)
        self.pointSelectButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pointSelectButton.setCheckable(True)
        self.pointSelectButton.setObjectName("pointSelectButton")
        self.buttonGroup.addButton(self.pointSelectButton)
        self.horizontalLayout_2.addWidget(self.pointSelectButton)
        self.regionSelectButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regionSelectButton.sizePolicy().hasHeightForWidth())
        self.regionSelectButton.setSizePolicy(sizePolicy)
        self.regionSelectButton.setCheckable(True)
        self.regionSelectButton.setObjectName("regionSelectButton")
        self.buttonGroup.addButton(self.regionSelectButton)
        self.horizontalLayout_2.addWidget(self.regionSelectButton)
        self.projectionLabel = QtWidgets.QLabel(self.centralwidget)
        self.projectionLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectionLabel.sizePolicy().hasHeightForWidth())
        self.projectionLabel.setSizePolicy(sizePolicy)
        self.projectionLabel.setObjectName("projectionLabel")
        self.horizontalLayout_2.addWidget(self.projectionLabel)
        self.projectionComboBox = QNoScrollComboBox(self.centralwidget)
        self.projectionComboBox.setEnabled(True)
        self.projectionComboBox.setObjectName("projectionComboBox")
        self.horizontalLayout_2.addWidget(self.projectionComboBox)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.cursorProbeText = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cursorProbeText.sizePolicy().hasHeightForWidth())
        self.cursorProbeText.setSizePolicy(sizePolicy)
        self.cursorProbeText.setMinimumSize(QtCore.QSize(250, 0))
        self.cursorProbeText.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(14)
        self.cursorProbeText.setFont(font)
        self.cursorProbeText.setScaledContents(False)
        self.cursorProbeText.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.cursorProbeText.setObjectName("cursorProbeText")
        self.horizontalLayout_2.addWidget(self.cursorProbeText)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.cursorProbeLayer = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cursorProbeLayer.sizePolicy().hasHeightForWidth())
        self.cursorProbeLayer.setSizePolicy(sizePolicy)
        self.cursorProbeLayer.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(14)
        self.cursorProbeLayer.setFont(font)
        self.cursorProbeLayer.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.cursorProbeLayer.setObjectName("cursorProbeLayer")
        self.horizontalLayout_2.addWidget(self.cursorProbeLayer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.mainMapWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainMapWidget.sizePolicy().hasHeightForWidth())
        self.mainMapWidget.setSizePolicy(sizePolicy)
        self.mainMapWidget.setObjectName("mainMapWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.mainMapWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.mainMapWidget)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.progressText = QtWidgets.QLabel(self.groupBox)
        self.progressText.setMinimumSize(QtCore.QSize(240, 0))
        self.progressText.setMaximumSize(QtCore.QSize(256, 16777215))
        self.progressText.setAlignment(QtCore.Qt.AlignCenter)
        self.progressText.setObjectName("progressText")
        self.verticalLayout_10.addWidget(self.progressText)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setMaximumSize(QtCore.QSize(256, 16777215))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_10.addWidget(self.progressBar)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.animationLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(14)
        self.animationLabel.setFont(font)
        self.animationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.animationLabel.setObjectName("animationLabel")
        self.verticalLayout_11.addWidget(self.animationLabel)
        self.animationSlider = QtWidgets.QSlider(self.groupBox)
        self.animationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.animationSlider.setObjectName("animationSlider")
        self.verticalLayout_11.addWidget(self.animationSlider)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.animBack = QtWidgets.QToolButton(self.groupBox)
        self.animBack.setToolTip("")
        self.animBack.setObjectName("animBack")
        self.horizontalLayout.addWidget(self.animBack)
        self.animPlayPause = QtWidgets.QToolButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(18)
        font.setItalic(False)
        self.animPlayPause.setFont(font)
        self.animPlayPause.setObjectName("animPlayPause")
        self.horizontalLayout.addWidget(self.animPlayPause)
        self.animForward = QtWidgets.QToolButton(self.groupBox)
        self.animForward.setObjectName("animForward")
        self.horizontalLayout.addWidget(self.animForward)
        self.verticalLayout_2.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1397, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.areaProbePane = QtWidgets.QDockWidget(MainWindow)
        self.areaProbePane.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable | QtWidgets.QDockWidget.DockWidgetMovable)
        self.areaProbePane.setObjectName("areaProbePane")
        self.probeWidget = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.probeWidget.sizePolicy().hasHeightForWidth())
        self.probeWidget.setSizePolicy(sizePolicy)
        self.probeWidget.setObjectName("probeWidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.probeWidget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.probeTabWidget = QtWidgets.QTabWidget(self.probeWidget)
        self.probeTabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.probeTabWidget.setObjectName("probeTabWidget")
        self.tab_plus = QtWidgets.QWidget()
        self.tab_plus.setObjectName("tab_plus")
        self.probeTabWidget.addTab(self.tab_plus, "")
        self.verticalLayout_12.addWidget(self.probeTabWidget)
        self.areaProbePane.setWidget(self.probeWidget)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.areaProbePane)
        self.layersPane = QtWidgets.QDockWidget(MainWindow)
        self.layersPane.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable | QtWidgets.QDockWidget.DockWidgetMovable)
        self.layersPane.setObjectName("layersPane")
        self.layersPaneWidget = QtWidgets.QWidget()
        self.layersPaneWidget.setObjectName("layersPaneWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layersPaneWidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.layerWidgetLayout = QtWidgets.QVBoxLayout()
        self.layerWidgetLayout.setObjectName("layerWidgetLayout")
        self.layerListView = QtWidgets.QTreeView(self.layersPaneWidget)
        self.layerListView.setObjectName("layerListView")
        self.layerWidgetLayout.addWidget(self.layerListView)
        self.verticalLayout_9.addLayout(self.layerWidgetLayout)
        self.layersPane.setWidget(self.layersPaneWidget)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.layersPane)
        self.layerDetailsPane = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layerDetailsPane.sizePolicy().hasHeightForWidth())
        self.layerDetailsPane.setSizePolicy(sizePolicy)
        self.layerDetailsPane.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable | QtWidgets.QDockWidget.DockWidgetMovable)
        self.layerDetailsPane.setObjectName("layerDetailsPane")
        self.layerInfoContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layerInfoContents.sizePolicy().hasHeightForWidth())
        self.layerInfoContents.setSizePolicy(sizePolicy)
        self.layerInfoContents.setObjectName("layerInfoContents")
        self.gridLayout = QtWidgets.QGridLayout(self.layerInfoContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.layerDetailsScrollArea = QtWidgets.QScrollArea(self.layerInfoContents)
        self.layerDetailsScrollArea.setWidgetResizable(True)
        self.layerDetailsScrollArea.setObjectName("layerDetailsScrollArea")
        self.layerDetailsContents = QtWidgets.QWidget()
        self.layerDetailsContents.setGeometry(QtCore.QRect(0, 0, 280, 76))
        self.layerDetailsContents.setObjectName("layerDetailsContents")
        self.layerDetailsScrollArea.setWidget(self.layerDetailsContents)
        self.gridLayout.addWidget(self.layerDetailsScrollArea, 0, 0, 1, 1)
        self.layerDetailsPane.setWidget(self.layerInfoContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.layerDetailsPane)
        self.rgbConfigPane = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rgbConfigPane.sizePolicy().hasHeightForWidth())
        self.rgbConfigPane.setSizePolicy(sizePolicy)
        self.rgbConfigPane.setMaximumSize(QtCore.QSize(800, 800))
        self.rgbConfigPane.setBaseSize(QtCore.QSize(128, 128))
        self.rgbConfigPane.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable | QtWidgets.QDockWidget.DockWidgetMovable)
        self.rgbConfigPane.setObjectName("rgbConfigPane")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 265, 524))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_8)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.redGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_8)
        self.redGroupBox.setObjectName("redGroupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.redGroupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.comboRed = QNoScrollComboBox(self.redGroupBox)
        self.comboRed.setObjectName("comboRed")
        self.verticalLayout_6.addWidget(self.comboRed)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.slideMinRed = QNoScrollSlider(self.redGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slideMinRed.sizePolicy().hasHeightForWidth())
        self.slideMinRed.setSizePolicy(sizePolicy)
        self.slideMinRed.setMaximum(32767)
        self.slideMinRed.setOrientation(QtCore.Qt.Horizontal)
        self.slideMinRed.setObjectName("slideMinRed")
        self.horizontalLayout_3.addWidget(self.slideMinRed)
        self.editMinRed = QtWidgets.QLineEdit(self.redGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editMinRed.sizePolicy().hasHeightForWidth())
        self.editMinRed.setSizePolicy(sizePolicy)
        self.editMinRed.setMinimumSize(QtCore.QSize(80, 0))
        self.editMinRed.setObjectName("editMinRed")
        self.horizontalLayout_3.addWidget(self.editMinRed)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.slideMaxRed = QNoScrollSlider(self.redGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slideMaxRed.sizePolicy().hasHeightForWidth())
        self.slideMaxRed.setSizePolicy(sizePolicy)
        self.slideMaxRed.setMaximum(32767)
        self.slideMaxRed.setOrientation(QtCore.Qt.Horizontal)
        self.slideMaxRed.setObjectName("slideMaxRed")
        self.horizontalLayout_4.addWidget(self.slideMaxRed)
        self.editMaxRed = QtWidgets.QLineEdit(self.redGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editMaxRed.sizePolicy().hasHeightForWidth())
        self.editMaxRed.setSizePolicy(sizePolicy)
        self.editMaxRed.setMinimumSize(QtCore.QSize(80, 0))
        self.editMaxRed.setObjectName("editMaxRed")
        self.horizontalLayout_4.addWidget(self.editMaxRed)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.redGammaLabel = QtWidgets.QLabel(self.redGroupBox)
        self.redGammaLabel.setObjectName("redGammaLabel")
        self.horizontalLayout_5.addWidget(self.redGammaLabel)
        self.redGammaSpinBox = QNoScrollDoubleSpinBox(self.redGroupBox)
        self.redGammaSpinBox.setDecimals(1)
        self.redGammaSpinBox.setMaximum(5.0)
        self.redGammaSpinBox.setSingleStep(0.1)
        self.redGammaSpinBox.setProperty("value", 1.0)
        self.redGammaSpinBox.setObjectName("redGammaSpinBox")
        self.horizontalLayout_5.addWidget(self.redGammaSpinBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_33.addWidget(self.redGroupBox)
        self.greenGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_8)
        self.greenGroupBox.setObjectName("greenGroupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.greenGroupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.comboGreen = QNoScrollComboBox(self.greenGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboGreen.sizePolicy().hasHeightForWidth())
        self.comboGreen.setSizePolicy(sizePolicy)
        self.comboGreen.setObjectName("comboGreen")
        self.verticalLayout_7.addWidget(self.comboGreen)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.slideMinGreen = QNoScrollSlider(self.greenGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slideMinGreen.sizePolicy().hasHeightForWidth())
        self.slideMinGreen.setSizePolicy(sizePolicy)
        self.slideMinGreen.setMaximum(32767)
        self.slideMinGreen.setOrientation(QtCore.Qt.Horizontal)
        self.slideMinGreen.setObjectName("slideMinGreen")
        self.horizontalLayout_43.addWidget(self.slideMinGreen)
        self.editMinGreen = QtWidgets.QLineEdit(self.greenGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editMinGreen.sizePolicy().hasHeightForWidth())
        self.editMinGreen.setSizePolicy(sizePolicy)
        self.editMinGreen.setMinimumSize(QtCore.QSize(80, 0))
        self.editMinGreen.setObjectName("editMinGreen")
        self.horizontalLayout_43.addWidget(self.editMinGreen)
        self.verticalLayout_7.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.slideMaxGreen = QNoScrollSlider(self.greenGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slideMaxGreen.sizePolicy().hasHeightForWidth())
        self.slideMaxGreen.setSizePolicy(sizePolicy)
        self.slideMaxGreen.setMaximum(32767)
        self.slideMaxGreen.setOrientation(QtCore.Qt.Horizontal)
        self.slideMaxGreen.setObjectName("slideMaxGreen")
        self.horizontalLayout_44.addWidget(self.slideMaxGreen)
        self.editMaxGreen = QtWidgets.QLineEdit(self.greenGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editMaxGreen.sizePolicy().hasHeightForWidth())
        self.editMaxGreen.setSizePolicy(sizePolicy)
        self.editMaxGreen.setMinimumSize(QtCore.QSize(80, 0))
        self.editMaxGreen.setObjectName("editMaxGreen")
        self.horizontalLayout_44.addWidget(self.editMaxGreen)
        self.verticalLayout_7.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.greenGammaLabel = QtWidgets.QLabel(self.greenGroupBox)
        self.greenGammaLabel.setObjectName("greenGammaLabel")
        self.horizontalLayout_6.addWidget(self.greenGammaLabel)
        self.greenGammaSpinBox = QNoScrollDoubleSpinBox(self.greenGroupBox)
        self.greenGammaSpinBox.setDecimals(1)
        self.greenGammaSpinBox.setMaximum(5.0)
        self.greenGammaSpinBox.setSingleStep(0.1)
        self.greenGammaSpinBox.setProperty("value", 1.0)
        self.greenGammaSpinBox.setObjectName("greenGammaSpinBox")
        self.horizontalLayout_6.addWidget(self.greenGammaSpinBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_33.addWidget(self.greenGroupBox)
        self.blueGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_8)
        self.blueGroupBox.setObjectName("blueGroupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.blueGroupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.comboBlue = QNoScrollComboBox(self.blueGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBlue.sizePolicy().hasHeightForWidth())
        self.comboBlue.setSizePolicy(sizePolicy)
        self.comboBlue.setObjectName("comboBlue")
        self.verticalLayout_8.addWidget(self.comboBlue)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.slideMinBlue = QNoScrollSlider(self.blueGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slideMinBlue.sizePolicy().hasHeightForWidth())
        self.slideMinBlue.setSizePolicy(sizePolicy)
        self.slideMinBlue.setMaximum(32767)
        self.slideMinBlue.setOrientation(QtCore.Qt.Horizontal)
        self.slideMinBlue.setObjectName("slideMinBlue")
        self.horizontalLayout_41.addWidget(self.slideMinBlue)
        self.editMinBlue = QtWidgets.QLineEdit(self.blueGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editMinBlue.sizePolicy().hasHeightForWidth())
        self.editMinBlue.setSizePolicy(sizePolicy)
        self.editMinBlue.setMinimumSize(QtCore.QSize(80, 0))
        self.editMinBlue.setObjectName("editMinBlue")
        self.horizontalLayout_41.addWidget(self.editMinBlue)
        self.verticalLayout_8.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.slideMaxBlue = QNoScrollSlider(self.blueGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slideMaxBlue.sizePolicy().hasHeightForWidth())
        self.slideMaxBlue.setSizePolicy(sizePolicy)
        self.slideMaxBlue.setMaximum(32767)
        self.slideMaxBlue.setOrientation(QtCore.Qt.Horizontal)
        self.slideMaxBlue.setObjectName("slideMaxBlue")
        self.horizontalLayout_42.addWidget(self.slideMaxBlue)
        self.editMaxBlue = QtWidgets.QLineEdit(self.blueGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editMaxBlue.sizePolicy().hasHeightForWidth())
        self.editMaxBlue.setSizePolicy(sizePolicy)
        self.editMaxBlue.setMinimumSize(QtCore.QSize(80, 0))
        self.editMaxBlue.setObjectName("editMaxBlue")
        self.horizontalLayout_42.addWidget(self.editMaxBlue)
        self.verticalLayout_8.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.blueGammaLabel = QtWidgets.QLabel(self.blueGroupBox)
        self.blueGammaLabel.setObjectName("blueGammaLabel")
        self.horizontalLayout_7.addWidget(self.blueGammaLabel)
        self.blueGammaSpinBox = QNoScrollDoubleSpinBox(self.blueGroupBox)
        self.blueGammaSpinBox.setDecimals(1)
        self.blueGammaSpinBox.setMaximum(5.0)
        self.blueGammaSpinBox.setSingleStep(0.1)
        self.blueGammaSpinBox.setProperty("value", 1.0)
        self.blueGammaSpinBox.setObjectName("blueGammaSpinBox")
        self.horizontalLayout_7.addWidget(self.blueGammaSpinBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout_33.addWidget(self.blueGroupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_8)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.rgbConfigPane.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.rgbConfigPane)
        self.timelinePane = QtWidgets.QDockWidget(MainWindow)
        self.timelinePane.setMinimumSize(QtCore.QSize(172, 102))
        self.timelinePane.setBaseSize(QtCore.QSize(0, 32))
        self.timelinePane.setFeatures(
            QtWidgets.QDockWidget.DockWidgetFloatable | QtWidgets.QDockWidget.DockWidgetMovable | QtWidgets.QDockWidget.DockWidgetVerticalTitleBar)
        self.timelinePane.setObjectName("timelinePane")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.timelineView = QtWidgets.QGraphicsView(self.dockWidgetContents_2)
        self.timelineView.setObjectName("timelineView")
        self.horizontalLayout_9.addWidget(self.timelineView)
        self.timelineScaleSlider = QtWidgets.QSlider(self.dockWidgetContents_2)
        self.timelineScaleSlider.setMaximum(1000)
        self.timelineScaleSlider.setSingleStep(10)
        self.timelineScaleSlider.setPageStep(100)
        self.timelineScaleSlider.setOrientation(QtCore.Qt.Vertical)
        self.timelineScaleSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.timelineScaleSlider.setTickInterval(100)
        self.timelineScaleSlider.setObjectName("timelineScaleSlider")
        self.horizontalLayout_9.addWidget(self.timelineScaleSlider)
        self.timelinePane.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.timelinePane)

        self.retranslateUi(MainWindow)
        self.probeTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SIFT |X.X.X|", None))
        self.panZoomToolButton.setToolTip(_translate("MainWindow", "Pan/Zoom Tool", None))
        self.panZoomToolButton.setStatusTip(_translate("MainWindow", "Left mouse click and drag pans the scene", None))
        self.panZoomToolButton.setText(_translate("MainWindow", "Pan/Zoom", None))
        self.pointSelectButton.setToolTip(_translate("MainWindow", "Point Probe Tool", None))
        self.pointSelectButton.setStatusTip(
            _translate("MainWindow", "Left mouse click probes a single point in the scene", None))
        self.pointSelectButton.setText(_translate("MainWindow", "Point", None))
        self.regionSelectButton.setToolTip(_translate("MainWindow", "Region Probe Tool", None))
        self.regionSelectButton.setStatusTip(
            _translate("MainWindow", "Left mouse click creates a polygon vertex (click initial vertex to complete)",
                       None))
        self.regionSelectButton.setText(_translate("MainWindow", "Region", None))
        self.projectionLabel.setText(_translate("MainWindow", "Projection:", None))
        self.cursorProbeText.setToolTip(_translate("MainWindow", "Value under cursor", None))
        self.cursorProbeText.setStatusTip(_translate("MainWindow", "Top layer data value under point probe", None))
        self.cursorProbeText.setText(_translate("MainWindow", "N/A", None))
        self.cursorProbeLayer.setText(_translate("MainWindow", "N/A", None))
        self.progressText.setText(_translate("MainWindow", "idle", None))
        self.progressBar.setToolTip(_translate("MainWindow", "Activity Progress", None))
        self.animationLabel.setText(_translate("MainWindow", "HH:MM", None))
        self.animBack.setStatusTip(_translate("MainWindow", "Step backward", None))
        self.animBack.setText(_translate("MainWindow", "|◀", None))
        self.animPlayPause.setStatusTip(_translate("MainWindow", "Start or stop animation", None))
        self.animPlayPause.setText(_translate("MainWindow", "▶", None))
        self.animForward.setStatusTip(_translate("MainWindow", "Step forward", None))
        self.animForward.setText(_translate("MainWindow", "▶|", None))
        self.areaProbePane.setWindowTitle(_translate("MainWindow", "Area Probe Graphs", None))
        self.probeTabWidget.setTabText(self.probeTabWidget.indexOf(self.tab_plus), _translate("MainWindow", "+", None))
        self.layersPane.setWindowTitle(_translate("MainWindow", "Layers", None))
        self.layerDetailsPane.setStatusTip(_translate("MainWindow", "Selected layer information", None))
        self.layerDetailsPane.setWindowTitle(_translate("MainWindow", "Layer Details", None))
        self.rgbConfigPane.setWindowTitle(_translate("MainWindow", "RGB Bounds", None))
        self.redGroupBox.setTitle(_translate("MainWindow", "Red", None))
        self.comboRed.setToolTip(_translate("MainWindow", "Red", None))
        self.comboRed.setStatusTip(_translate("MainWindow", "Red channel", None))
        self.slideMinRed.setToolTip(_translate("MainWindow", "value at 0% red", None))
        self.slideMaxRed.setToolTip(_translate("MainWindow", "value at 100% red", None))
        self.redGammaLabel.setText(_translate("MainWindow", "Gamma: ", None))
        self.greenGroupBox.setTitle(_translate("MainWindow", "Green", None))
        self.comboGreen.setToolTip(_translate("MainWindow", "Green", None))
        self.comboGreen.setStatusTip(_translate("MainWindow", "Red channel", None))
        self.slideMinGreen.setToolTip(_translate("MainWindow", "value at 0% green", None))
        self.slideMaxGreen.setToolTip(_translate("MainWindow", "value at 100% green", None))
        self.greenGammaLabel.setText(_translate("MainWindow", "Gamma: ", None))
        self.blueGroupBox.setTitle(_translate("MainWindow", "Blue", None))
        self.comboBlue.setToolTip(_translate("MainWindow", "Red", None))
        self.comboBlue.setStatusTip(_translate("MainWindow", "Red channel", None))
        self.slideMinBlue.setToolTip(_translate("MainWindow", "value at 0% blue", None))
        self.slideMaxBlue.setToolTip(_translate("MainWindow", "value at 100% blue", None))
        self.blueGammaLabel.setText(_translate("MainWindow", "Gamma: ", None))
        self.timelinePane.setWindowTitle(_translate("MainWindow", "Timeline", None))


from uwsift.ui.custom_widgets import QNoScrollComboBox, QNoScrollDoubleSpinBox, QNoScrollSlider
