# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resample_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ResampleDialog(object):
    def setupUi(self, ResampleDialog):
        ResampleDialog.setObjectName("ResampleDialog")
        ResampleDialog.resize(310, 360)
        self.buttonBox = QtWidgets.QDialogButtonBox(ResampleDialog)
        self.buttonBox.setGeometry(QtCore.QRect(120, 320, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.areaExGroupBox = QtWidgets.QGroupBox(ResampleDialog)
        self.areaExGroupBox.setGeometry(QtCore.QRect(160, 150, 131, 121))
        self.areaExGroupBox.setObjectName("areaExGroupBox")
        self.areaExUpperRightYLineEdit = QtWidgets.QLineEdit(self.areaExGroupBox)
        self.areaExUpperRightYLineEdit.setGeometry(QtCore.QRect(10, 90, 113, 21))
        self.areaExUpperRightYLineEdit.setObjectName("areaExUpperRightYLineEdit")
        self.areaExLowerLeftYLineEdit = QtWidgets.QLineEdit(self.areaExGroupBox)
        self.areaExLowerLeftYLineEdit.setGeometry(QtCore.QRect(10, 50, 113, 21))
        self.areaExLowerLeftYLineEdit.setObjectName("areaExLowerLeftYLineEdit")
        self.areaExLowerLeftXLineEdit = QtWidgets.QLineEdit(self.areaExGroupBox)
        self.areaExLowerLeftXLineEdit.setGeometry(QtCore.QRect(10, 30, 113, 21))
        self.areaExLowerLeftXLineEdit.setObjectName("areaExLowerLeftXLineEdit")
        self.areaExUpperRightXLineEdit = QtWidgets.QLineEdit(self.areaExGroupBox)
        self.areaExUpperRightXLineEdit.setGeometry(QtCore.QRect(10, 70, 113, 21))
        self.areaExUpperRightXLineEdit.setObjectName("areaExUpperRightXLineEdit")
        self.resGroupBox = QtWidgets.QGroupBox(ResampleDialog)
        self.resGroupBox.setGeometry(QtCore.QRect(20, 150, 131, 81))
        self.resGroupBox.setObjectName("resGroupBox")
        self.resXLineEdit = QtWidgets.QLineEdit(self.resGroupBox)
        self.resXLineEdit.setGeometry(QtCore.QRect(10, 30, 113, 21))
        self.resXLineEdit.setText("")
        self.resXLineEdit.setObjectName("resXLineEdit")
        self.resYLineEdit = QtWidgets.QLineEdit(self.resGroupBox)
        self.resYLineEdit.setGeometry(QtCore.QRect(10, 50, 113, 21))
        self.resYLineEdit.setObjectName("resYLineEdit")
        self.shapeGroupBox = QtWidgets.QGroupBox(ResampleDialog)
        self.shapeGroupBox.setGeometry(QtCore.QRect(20, 230, 131, 81))
        self.shapeGroupBox.setObjectName("shapeGroupBox")
        self.shapeYLineEdit = QtWidgets.QLineEdit(self.shapeGroupBox)
        self.shapeYLineEdit.setGeometry(QtCore.QRect(10, 50, 113, 21))
        self.shapeYLineEdit.setText("")
        self.shapeYLineEdit.setObjectName("shapeYLineEdit")
        self.shapeXLineEdit = QtWidgets.QLineEdit(self.shapeGroupBox)
        self.shapeXLineEdit.setGeometry(QtCore.QRect(10, 30, 113, 21))
        self.shapeXLineEdit.setText("")
        self.shapeXLineEdit.setObjectName("shapeXLineEdit")
        self.resamplingMethodGroupBox = QtWidgets.QGroupBox(ResampleDialog)
        self.resamplingMethodGroupBox.setGeometry(QtCore.QRect(20, 10, 271, 71))
        self.resamplingMethodGroupBox.setObjectName("resamplingMethodGroupBox")
        self.resamplingMethodComboBox = QtWidgets.QComboBox(self.resamplingMethodGroupBox)
        self.resamplingMethodComboBox.setGeometry(QtCore.QRect(10, 30, 251, 26))
        self.resamplingMethodComboBox.setObjectName("resamplingMethodComboBox")
        self.projectionGroupBox = QtWidgets.QGroupBox(ResampleDialog)
        self.projectionGroupBox.setGeometry(QtCore.QRect(20, 80, 271, 71))
        self.projectionGroupBox.setObjectName("projectionGroupBox")
        self.projectionComboBox = QtWidgets.QComboBox(self.projectionGroupBox)
        self.projectionComboBox.setGeometry(QtCore.QRect(10, 30, 251, 26))
        self.projectionComboBox.setObjectName("projectionComboBox")

        self.retranslateUi(ResampleDialog)
        self.buttonBox.accepted.connect(ResampleDialog.accept)
        self.buttonBox.rejected.connect(ResampleDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ResampleDialog)

    def retranslateUi(self, ResampleDialog):
        _translate = QtCore.QCoreApplication.translate
        ResampleDialog.setWindowTitle(_translate("ResampleDialog", "Resample"))
        self.areaExGroupBox.setTitle(_translate("ResampleDialog", "Area Extent"))
        self.areaExUpperRightYLineEdit.setPlaceholderText(_translate("ResampleDialog", "upper right y"))
        self.areaExLowerLeftYLineEdit.setPlaceholderText(_translate("ResampleDialog", "lower left y"))
        self.areaExLowerLeftXLineEdit.setPlaceholderText(_translate("ResampleDialog", "lower left x"))
        self.areaExUpperRightXLineEdit.setPlaceholderText(_translate("ResampleDialog", "upper right x"))
        self.resGroupBox.setTitle(_translate("ResampleDialog", "Resolution"))
        self.resXLineEdit.setPlaceholderText(_translate("ResampleDialog", "pixel size in x dir"))
        self.resYLineEdit.setPlaceholderText(_translate("ResampleDialog", "pixel size in y dir"))
        self.shapeGroupBox.setTitle(_translate("ResampleDialog", "Shape"))
        self.shapeYLineEdit.setPlaceholderText(_translate("ResampleDialog", "columns"))
        self.shapeXLineEdit.setPlaceholderText(_translate("ResampleDialog", "rows"))
        self.resamplingMethodGroupBox.setTitle(_translate("ResampleDialog", "Resampling Method"))
        self.projectionGroupBox.setTitle(_translate("ResampleDialog", "Projection"))

