name: test-environment
channels:
  - conda-forge
dependencies:
  # limiting python due to ecmwflibs
  - python<=3.12
  - appdirs
  - defusedxml
  - Cython
  - imageio
  - imageio-ffmpeg
  - matplotlib
  - numba
  - numpy
  - pyproj
  - pyshp
  - pyqt
  - pyqtgraph
  - pyqtwebengine
  - satpy
  - scikit-image
  - shapely
  - sqlalchemy
  - vispy
  ### Satpy-only Optional Deps
  - bottleneck
  - dask
  - donfig
  - cfgrib
  - fsspec
  - h5netcdf
  - h5py
  - hdf5plugin
  - netcdf4
  - pillow
  - pooch
  - pyhdf
  - pyresample
  - python-geotiepoints
  - pyyaml
  - rasterio
  - rioxarray
  - xarray
  - zarr
  ### Development/Test dependencies
  - coveralls
  - coverage
  - codecov
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-qt
  - pip
  - sphinx
  ### Pip Dependencies
  - pip:
    - trollsift
    - trollimage
    - pyspectral
    - pyorbital
    # docs:
    - blockdiag
    - sphinx
    - sphinx-rtd-theme
    - sphinxcontrib-seqdiag
    - sphinxcontrib-blockdiag
    - psutil
    - eccodes>=2.37 # 2.37.0 has ecmwflibs integrated
