{% set data = load_setup_py_data() %}

package:
  name: sift
  version: {{ data.get('version') }}

source:
  path: ../../
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python >=3.6
    - setuptools
    - numpy >=1.12
    - gdal >=2.1,<2.2
    - rasterio
    - matplotlib
    - scipy
    - numba >=0.30
    - pyproj >=1.9.4
    - vispy ==0.5.0dev2
    - goesr >=0.4.2 # via Ray Garcia, on sift channel
    - pyopengl
    - netcdf4
    - h5py
    - pillow
    - pyshp
    - shapely
    - sqlalchemy
    - pyqt <5
    - appdirs
    - cython >=0.17 # [win]
    # this is only needed because of a weird bug with netcdf4
    # https://github.com/conda-forge/netcdf4-feedstock/issues/33
    - cython >=0.19 # [unix]

  run:
    - python >=3.6
    - numpy >=1.12
    - gdal >=2.1,<2.2
    - rasterio
    - matplotlib
    - scipy
    - numba >=0.30
    - pyproj >=1.9.4
    - vispy ==0.5.0dev2
    - goesr >=0.4.2 # via Ray Garcia, on sift channel
    - pyopengl
    - netcdf4
    - h5py
    - pillow
    - pyshp
    - shapely
    - sqlalchemy
    - pyqt <5
    - appdirs

test:
  commands:
    - python -m sift -h
    - python -c "import gdal"
    - python -c "from PyQt4 import QtGui, QtCore"
    - python -c "from netCDF4 import Dataset"
    - python -c "import h5py"

about:
  #home: The package home page
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: 'Visualization Tool for Geostationary satellite imagery data'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
